name: test_pr

on: 
  pull_request:

jobs:
  test_pr:
    name: test_pr
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    services:
      neo4j:
        image: neo4j:4.2.1
        env:
          NEO4J_AUTH: none
          NEO4JLABS_PLUGINS: '["apoc"]'
        ports:
          - '7474:7474'
          - '7687:7687'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov codecov neo4j==4.0.2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    

      - name: Set up Neo4j data
        run: |
          python tests/initialize_db.py "${GITHUB_SHA}"

      - name: Run pytest
        run: |
          export PYTHONPATH=$(pwd)
          pytest --cov=reasoner --cov-report=xml tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
